// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {state} from '../models';
import {claude} from '../models';
import {main} from '../models';
import {testing} from '../models';
import {docker} from '../models';
import {git} from '../models';
import {structure} from '../models';

export function AddApprovedClient(arg1:string):Promise<remote.ApprovedClient>;

export function AddBookmark(arg1:string,arg2:string,arg3:string):Promise<state.Bookmark>;

export function AddHook(arg1:string,arg2:claude.Hook):Promise<void>;

export function AddHookEntry(arg1:string,arg2:claude.HookEntry):Promise<void>;

export function AddMCPServer(arg1:string,arg2:claude.MCPServer):Promise<void>;

export function AddTestRun(arg1:string,arg2:state.TestRun):Promise<void>;

export function CheckLibraryStatus(arg1:string,arg2:Array<string>):Promise<Array<claude.LibStatus>>;

export function CheckProjectCoverage(arg1:string):Promise<void>;

export function ClearTestDiscoveryCache(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateGlobalPrompt(arg1:state.Prompt):Promise<state.Prompt>;

export function CreateHookScript(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<state.ProjectState>;

export function CreatePrompt(arg1:string,arg2:state.Prompt):Promise<state.Prompt>;

export function CreatePromptCategory(arg1:string,arg2:string,arg3:boolean):Promise<state.PromptCategory>;

export function CreateTerminal(arg1:string,arg2:string,arg3:string):Promise<main.TerminalInfo>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteGlobalPrompt(arg1:string):Promise<void>;

export function DeleteHookScript(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string,arg2:string):Promise<void>;

export function DeletePromptCategory(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteScreenshot(arg1:string,arg2:string):Promise<void>;

export function GetActiveProject():Promise<string>;

export function GetAgentContent(arg1:string):Promise<string>;

export function GetAllTestSummaries():Promise<Record<string, testing.TestSummary>>;

export function GetApprovedClients():Promise<Array<remote.ApprovedClient>>;

export function GetAvailableSkills():Promise<Array<claude.Skill>>;

export function GetBookmarks(arg1:string):Promise<Array<state.Bookmark>>;

export function GetClaudemd(arg1:string):Promise<string>;

export function GetCommandContent(arg1:string):Promise<string>;

export function GetContainerLogs(arg1:string):Promise<string>;

export function GetContainers(arg1:boolean):Promise<Array<docker.Container>>;

export function GetDefaultColors():Promise<Array<string>>;

export function GetDefaultIcons():Promise<Array<string>>;

export function GetDockerProjectContainers(arg1:string):Promise<Array<docker.Container>>;

export function GetGitChangedFiles(arg1:string):Promise<Array<git.ChangedFile>>;

export function GetGitCurrentBranch(arg1:string):Promise<string>;

export function GetGitFileDiff(arg1:string,arg2:string):Promise<git.FileDiff>;

export function GetGitHistory(arg1:string,arg2:number):Promise<Array<git.CommitInfo>>;

export function GetGitStatus(arg1:string):Promise<Record<string, number>>;

export function GetGlobalAgents():Promise<Array<claude.Agent>>;

export function GetGlobalCommands():Promise<Array<claude.Command>>;

export function GetGlobalPromptCategories():Promise<Array<state.PromptCategory>>;

export function GetGlobalPrompts():Promise<Array<state.Prompt>>;

export function GetHookScriptContent(arg1:string,arg2:string):Promise<string>;

export function GetInstalledSkills(arg1:string):Promise<Array<string>>;

export function GetNotes(arg1:string):Promise<string>;

export function GetPackageJSONScripts(arg1:string):Promise<Record<string, string>>;

export function GetProject(arg1:string):Promise<state.ProjectState>;

export function GetProjectAgents(arg1:string):Promise<Array<claude.Agent>>;

export function GetProjectCommands(arg1:string):Promise<Array<claude.Command>>;

export function GetProjectCoverage(arg1:string):Promise<testing.CoverageSummary>;

export function GetProjectCoverageHistory(arg1:string):Promise<testing.CoverageHistory>;

export function GetProjectDependencies(arg1:string):Promise<Record<string, string>>;

export function GetProjectFolderHierarchy(arg1:string):Promise<structure.FileNode>;

export function GetProjectHookScripts(arg1:string):Promise<Array<string>>;

export function GetProjectHooks(arg1:string):Promise<Array<claude.Hook>>;

export function GetProjectHooksDetailed(arg1:string):Promise<Array<claude.HookEntry>>;

export function GetProjectMCPServers(arg1:string):Promise<Array<claude.MCPServer>>;

export function GetProjectPrompts(arg1:string):Promise<Array<state.Prompt>>;

export function GetProjectStructure(arg1:string):Promise<structure.FileNode>;

export function GetProjectTerminals(arg1:string):Promise<Array<main.TerminalInfo>>;

export function GetProjects():Promise<Array<state.ProjectState>>;

export function GetPromptCategories(arg1:string):Promise<Array<state.PromptCategory>>;

export function GetRemoteAccessClients():Promise<Array<remote.ClientInfo>>;

export function GetRemoteAccessStatus():Promise<main.RemoteAccessStatus>;

export function GetScreenshots(arg1:string):Promise<Array<main.Screenshot>>;

export function GetState():Promise<state.AppState>;

export function GetTemplateAgents():Promise<Array<claude.TemplateItem>>;

export function GetTemplateCommands():Promise<Array<claude.TemplateItem>>;

export function GetTemplateContent(arg1:string):Promise<string>;

export function GetTemplateHooks():Promise<Array<claude.HookEntry>>;

export function GetTemplateMCPServers():Promise<Array<claude.MCPServer>>;

export function GetTemplateRepoPath():Promise<string>;

export function GetTemplateRules():Promise<Array<claude.TemplateItem>>;

export function GetTemplateSkills():Promise<Array<claude.TemplateItem>>;

export function GetTerminalTheme():Promise<string>;

export function GetTerminals():Promise<Array<main.TerminalInfo>>;

export function GetTestDiscovery(arg1:string):Promise<testing.TestDiscovery>;

export function GetTestHistory(arg1:string):Promise<Array<state.TestRun>>;

export function GetTestSummary(arg1:string):Promise<testing.TestSummary>;

export function GetTodos(arg1:string):Promise<Array<state.TodoItem>>;

export function GetUserMCPServers():Promise<Array<claude.MCPServer>>;

export function IncrementPromptUsage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function InstallHook(arg1:string,arg2:string):Promise<void>;

export function InstallSkill(arg1:string,arg2:string):Promise<void>;

export function InstallTemplateAgent(arg1:string,arg2:string):Promise<void>;

export function InstallTemplateCommand(arg1:string,arg2:string):Promise<void>;

export function InstallTemplateHook(arg1:string,arg2:claude.HookEntry):Promise<void>;

export function InstallTemplateRule(arg1:string,arg2:string):Promise<void>;

export function InstallTemplateSkill(arg1:string,arg2:string):Promise<void>;

export function IsDevMode():Promise<boolean>;

export function IsDockerAvailable():Promise<boolean>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function IsTestRunning():Promise<boolean>;

export function Log(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function PauseTerminal(arg1:string):Promise<void>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RefreshNgrokURL():Promise<string>;

export function RemoteCreateTerminal(arg1:string,arg2:string):Promise<remote.TerminalInfo>;

export function RemoteDeleteTerminal(arg1:string,arg2:string):Promise<void>;

export function RemoteGetProjects():Promise<Array<remote.ProjectInfo>>;

export function RemoteRenameTerminal(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveApprovedClient(arg1:string):Promise<void>;

export function RemoveBookmark(arg1:string,arg2:string):Promise<void>;

export function RemoveHook(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveMCPServer(arg1:string,arg2:string):Promise<void>;

export function ResetTestState(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function ResumeTerminal(arg1:string):Promise<void>;

export function SaveAgentContent(arg1:string,arg2:string):Promise<void>;

export function SaveClaudemd(arg1:string,arg2:string):Promise<void>;

export function SaveCommandContent(arg1:string,arg2:string):Promise<void>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SaveNotes(arg1:string,arg2:string):Promise<void>;

export function SaveScreenshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveTestHistory(arg1:string,arg2:Array<state.TestRun>):Promise<void>;

export function SaveTodos(arg1:string,arg2:Array<state.TodoItem>):Promise<void>;

export function ScanProjectTests(arg1:string):Promise<testing.TestDiscovery>;

export function SelectDirectory():Promise<string>;

export function SetActiveProject(arg1:string):Promise<void>;

export function SetActiveTerminal(arg1:string,arg2:string):Promise<void>;

export function SetTerminalTheme(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartRemoteAccess(arg1:remote.Config):Promise<main.RemoteAccessStatus>;

export function StopContainer(arg1:string):Promise<void>;

export function StopRemoteAccess():Promise<void>;

export function TogglePromptPinned(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UnwatchProjectCoverage(arg1:string):Promise<void>;

export function UpdateBrowserState(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:number):Promise<void>;

export function UpdateBrowserTabs(arg1:string,arg2:Array<state.BrowserTab>,arg3:string):Promise<void>;

export function UpdateGlobalPrompt(arg1:string,arg2:state.Prompt):Promise<void>;

export function UpdateProject(arg1:state.ProjectState):Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:state.Prompt):Promise<void>;

export function UpdateUIState(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<void>;

export function WatchProjectCoverage(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
