// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApprovedClient(arg1) {
  return window['go']['main']['App']['AddApprovedClient'](arg1);
}

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2, arg3);
}

export function AddHook(arg1, arg2) {
  return window['go']['main']['App']['AddHook'](arg1, arg2);
}

export function AddHookEntry(arg1, arg2) {
  return window['go']['main']['App']['AddHookEntry'](arg1, arg2);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AddTestRun(arg1, arg2) {
  return window['go']['main']['App']['AddTestRun'](arg1, arg2);
}

export function CheckLibraryStatus(arg1, arg2) {
  return window['go']['main']['App']['CheckLibraryStatus'](arg1, arg2);
}

export function CheckProjectCoverage(arg1) {
  return window['go']['main']['App']['CheckProjectCoverage'](arg1);
}

export function ClearTestDiscoveryCache(arg1) {
  return window['go']['main']['App']['ClearTestDiscoveryCache'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCommand'](arg1, arg2, arg3);
}

export function CreateGlobalPrompt(arg1) {
  return window['go']['main']['App']['CreateGlobalPrompt'](arg1);
}

export function CreateHookScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateHookScript'](arg1, arg2, arg3);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreatePrompt(arg1, arg2) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2);
}

export function CreatePromptCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePromptCategory'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteGlobalPrompt(arg1) {
  return window['go']['main']['App']['DeleteGlobalPrompt'](arg1);
}

export function DeleteHookScript(arg1, arg2) {
  return window['go']['main']['App']['DeleteHookScript'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeletePrompt(arg1, arg2) {
  return window['go']['main']['App']['DeletePrompt'](arg1, arg2);
}

export function DeletePromptCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePromptCategory'](arg1, arg2, arg3);
}

export function DeleteScreenshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1, arg2);
}

export function GetActiveProject() {
  return window['go']['main']['App']['GetActiveProject']();
}

export function GetAgentContent(arg1) {
  return window['go']['main']['App']['GetAgentContent'](arg1);
}

export function GetAllTestSummaries() {
  return window['go']['main']['App']['GetAllTestSummaries']();
}

export function GetApprovedClients() {
  return window['go']['main']['App']['GetApprovedClients']();
}

export function GetAvailableSkills() {
  return window['go']['main']['App']['GetAvailableSkills']();
}

export function GetBookmarks(arg1) {
  return window['go']['main']['App']['GetBookmarks'](arg1);
}

export function GetClaudemd(arg1) {
  return window['go']['main']['App']['GetClaudemd'](arg1);
}

export function GetCommandContent(arg1) {
  return window['go']['main']['App']['GetCommandContent'](arg1);
}

export function GetContainerLogs(arg1) {
  return window['go']['main']['App']['GetContainerLogs'](arg1);
}

export function GetContainers(arg1) {
  return window['go']['main']['App']['GetContainers'](arg1);
}

export function GetDefaultColors() {
  return window['go']['main']['App']['GetDefaultColors']();
}

export function GetDefaultIcons() {
  return window['go']['main']['App']['GetDefaultIcons']();
}

export function GetDockerProjectContainers(arg1) {
  return window['go']['main']['App']['GetDockerProjectContainers'](arg1);
}

export function GetGitChangedFiles(arg1) {
  return window['go']['main']['App']['GetGitChangedFiles'](arg1);
}

export function GetGitCurrentBranch(arg1) {
  return window['go']['main']['App']['GetGitCurrentBranch'](arg1);
}

export function GetGitFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitFileDiff'](arg1, arg2);
}

export function GetGitHistory(arg1, arg2) {
  return window['go']['main']['App']['GetGitHistory'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetGlobalAgents() {
  return window['go']['main']['App']['GetGlobalAgents']();
}

export function GetGlobalCommands() {
  return window['go']['main']['App']['GetGlobalCommands']();
}

export function GetGlobalPromptCategories() {
  return window['go']['main']['App']['GetGlobalPromptCategories']();
}

export function GetGlobalPrompts() {
  return window['go']['main']['App']['GetGlobalPrompts']();
}

export function GetHookScriptContent(arg1, arg2) {
  return window['go']['main']['App']['GetHookScriptContent'](arg1, arg2);
}

export function GetInstalledSkills(arg1) {
  return window['go']['main']['App']['GetInstalledSkills'](arg1);
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetPackageJSONScripts(arg1) {
  return window['go']['main']['App']['GetPackageJSONScripts'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectAgents(arg1) {
  return window['go']['main']['App']['GetProjectAgents'](arg1);
}

export function GetProjectCommands(arg1) {
  return window['go']['main']['App']['GetProjectCommands'](arg1);
}

export function GetProjectCoverage(arg1) {
  return window['go']['main']['App']['GetProjectCoverage'](arg1);
}

export function GetProjectCoverageHistory(arg1) {
  return window['go']['main']['App']['GetProjectCoverageHistory'](arg1);
}

export function GetProjectDependencies(arg1) {
  return window['go']['main']['App']['GetProjectDependencies'](arg1);
}

export function GetProjectFolderHierarchy(arg1) {
  return window['go']['main']['App']['GetProjectFolderHierarchy'](arg1);
}

export function GetProjectHookScripts(arg1) {
  return window['go']['main']['App']['GetProjectHookScripts'](arg1);
}

export function GetProjectHooks(arg1) {
  return window['go']['main']['App']['GetProjectHooks'](arg1);
}

export function GetProjectHooksDetailed(arg1) {
  return window['go']['main']['App']['GetProjectHooksDetailed'](arg1);
}

export function GetProjectMCPServers(arg1) {
  return window['go']['main']['App']['GetProjectMCPServers'](arg1);
}

export function GetProjectPrompts(arg1) {
  return window['go']['main']['App']['GetProjectPrompts'](arg1);
}

export function GetProjectStructure(arg1) {
  return window['go']['main']['App']['GetProjectStructure'](arg1);
}

export function GetProjectTerminals(arg1) {
  return window['go']['main']['App']['GetProjectTerminals'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetPromptCategories(arg1) {
  return window['go']['main']['App']['GetPromptCategories'](arg1);
}

export function GetRemoteAccessClients() {
  return window['go']['main']['App']['GetRemoteAccessClients']();
}

export function GetRemoteAccessStatus() {
  return window['go']['main']['App']['GetRemoteAccessStatus']();
}

export function GetScreenshots(arg1) {
  return window['go']['main']['App']['GetScreenshots'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTemplateAgents() {
  return window['go']['main']['App']['GetTemplateAgents']();
}

export function GetTemplateCommands() {
  return window['go']['main']['App']['GetTemplateCommands']();
}

export function GetTemplateContent(arg1) {
  return window['go']['main']['App']['GetTemplateContent'](arg1);
}

export function GetTemplateHooks() {
  return window['go']['main']['App']['GetTemplateHooks']();
}

export function GetTemplateMCPServers() {
  return window['go']['main']['App']['GetTemplateMCPServers']();
}

export function GetTemplateRepoPath() {
  return window['go']['main']['App']['GetTemplateRepoPath']();
}

export function GetTemplateRules() {
  return window['go']['main']['App']['GetTemplateRules']();
}

export function GetTemplateSkills() {
  return window['go']['main']['App']['GetTemplateSkills']();
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function GetTestDiscovery(arg1) {
  return window['go']['main']['App']['GetTestDiscovery'](arg1);
}

export function GetTestHistory(arg1) {
  return window['go']['main']['App']['GetTestHistory'](arg1);
}

export function GetTestSummary(arg1) {
  return window['go']['main']['App']['GetTestSummary'](arg1);
}

export function GetTodos(arg1) {
  return window['go']['main']['App']['GetTodos'](arg1);
}

export function GetUserMCPServers() {
  return window['go']['main']['App']['GetUserMCPServers']();
}

export function IncrementPromptUsage(arg1, arg2, arg3) {
  return window['go']['main']['App']['IncrementPromptUsage'](arg1, arg2, arg3);
}

export function InstallHook(arg1, arg2) {
  return window['go']['main']['App']['InstallHook'](arg1, arg2);
}

export function InstallSkill(arg1, arg2) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2);
}

export function InstallTemplateAgent(arg1, arg2) {
  return window['go']['main']['App']['InstallTemplateAgent'](arg1, arg2);
}

export function InstallTemplateCommand(arg1, arg2) {
  return window['go']['main']['App']['InstallTemplateCommand'](arg1, arg2);
}

export function InstallTemplateHook(arg1, arg2) {
  return window['go']['main']['App']['InstallTemplateHook'](arg1, arg2);
}

export function InstallTemplateRule(arg1, arg2) {
  return window['go']['main']['App']['InstallTemplateRule'](arg1, arg2);
}

export function InstallTemplateSkill(arg1, arg2) {
  return window['go']['main']['App']['InstallTemplateSkill'](arg1, arg2);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function IsDockerAvailable() {
  return window['go']['main']['App']['IsDockerAvailable']();
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function IsTestRunning() {
  return window['go']['main']['App']['IsTestRunning']();
}

export function Log(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Log'](arg1, arg2, arg3, arg4);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RefreshNgrokURL() {
  return window['go']['main']['App']['RefreshNgrokURL']();
}

export function RemoteCreateTerminal(arg1, arg2) {
  return window['go']['main']['App']['RemoteCreateTerminal'](arg1, arg2);
}

export function RemoteDeleteTerminal(arg1, arg2) {
  return window['go']['main']['App']['RemoteDeleteTerminal'](arg1, arg2);
}

export function RemoteGetProjects() {
  return window['go']['main']['App']['RemoteGetProjects']();
}

export function RemoteRenameTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteRenameTerminal'](arg1, arg2, arg3);
}

export function RemoveApprovedClient(arg1) {
  return window['go']['main']['App']['RemoveApprovedClient'](arg1);
}

export function RemoveBookmark(arg1, arg2) {
  return window['go']['main']['App']['RemoveBookmark'](arg1, arg2);
}

export function RemoveHook(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveHook'](arg1, arg2, arg3);
}

export function RemoveMCPServer(arg1, arg2) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1, arg2);
}

export function ResetTestState(arg1) {
  return window['go']['main']['App']['ResetTestState'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function SaveAgentContent(arg1, arg2) {
  return window['go']['main']['App']['SaveAgentContent'](arg1, arg2);
}

export function SaveClaudemd(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudemd'](arg1, arg2);
}

export function SaveCommandContent(arg1, arg2) {
  return window['go']['main']['App']['SaveCommandContent'](arg1, arg2);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SaveNotes(arg1, arg2) {
  return window['go']['main']['App']['SaveNotes'](arg1, arg2);
}

export function SaveScreenshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2, arg3);
}

export function SaveTestHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveTestHistory'](arg1, arg2);
}

export function SaveTodos(arg1, arg2) {
  return window['go']['main']['App']['SaveTodos'](arg1, arg2);
}

export function ScanProjectTests(arg1) {
  return window['go']['main']['App']['ScanProjectTests'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function SetActiveTerminal(arg1, arg2) {
  return window['go']['main']['App']['SetActiveTerminal'](arg1, arg2);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartRemoteAccess(arg1) {
  return window['go']['main']['App']['StartRemoteAccess'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopRemoteAccess() {
  return window['go']['main']['App']['StopRemoteAccess']();
}

export function TogglePromptPinned(arg1, arg2, arg3) {
  return window['go']['main']['App']['TogglePromptPinned'](arg1, arg2, arg3);
}

export function UnwatchProjectCoverage(arg1) {
  return window['go']['main']['App']['UnwatchProjectCoverage'](arg1);
}

export function UpdateBrowserState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateBrowserState'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateBrowserTabs(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateBrowserTabs'](arg1, arg2, arg3);
}

export function UpdateGlobalPrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateGlobalPrompt'](arg1, arg2);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdatePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3);
}

export function UpdateUIState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateUIState'](arg1, arg2, arg3, arg4);
}

export function WatchProjectCoverage(arg1) {
  return window['go']['main']['App']['WatchProjectCoverage'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
